site_name: MyAsk CLI Documentation
nav:
  - Application: https://myask.io
  - Github: https://github.com/MyAsk-IO/cli
  - Documention Home: index.md
  - Installing CLI: CLI.md
  - Models Overview: ai-models/OVERVIEW.md
  - Code Refactoring: ai-models/REFACTORING.md
  - ask.ts Source File: ai-models/code-files/prompt.ts.md